"""Online semantic_weight tuning (v1.23.0).

Reads `ranking_events` from `~/.doc-index/telemetry.db` for one repo
(or every repo), splits events by `semantic_used`, compares mean
confidence with vs without the semantic channel, and proposes a
±0.05 step on the per-repo `semantic_weight` when the gap is large
enough to act on.

Bounded:

  - `min_events` (default 50) gates against overfitting on a few
    early calls.
  - Step size ±0.05 keeps drift gradual; clamped to [0.10, 0.95] so
    we never fully disable either channel.

    ⚠ The ceiling was 0.85 through v1.124.3. jdoc#106 measured a
    5,315-section corpus where every slice improved monotonically to
    0.95 and only 1.0 cost keyword recall (93.3% → 86.7%), so 0.85 sat
    below the corpus optimum and the resolver silently clamped a
    hand-written 0.95 back down to it. 1.0 is the value worth
    excluding, not 0.95.
  - Threshold |delta_conf| >= 0.05 — smaller swings stay flat.
  - `max_age_days` (default 90) windows the ledger read so stale
    events can't anchor weights to an old query distribution
    (0 = lifetime).

Persisted at `~/.doc-index/tuning.jsonc`:

    {
      "repos": {
        "<owner>/<name>": {
          "semantic_weight": 0.55,
          "learned_from_events": 312,
          "captured_at": "2026-04-26T13:42:11Z"
        },
        ...
      }
    }

Mirrors jcodemunch v1.79.0 in shape; pure-Python, no numpy.
"""

from __future__ import annotations

import json
import re
import threading
import time
from pathlib import Path
from typing import Optional

from ..storage.token_tracker import ranking_db_query

DEFAULT_SEMANTIC_WEIGHT = 0.5
SEMANTIC_WEIGHT_BOUNDS = (0.10, 0.95)
MIN_EVENTS = 50
DELTA_CONF_THRESHOLD = 0.05
STEP = 0.05
# jdoc#106: the step scales with the measured gap. A flat 0.05 needed seven
# successful rounds (350+ qualifying events) to cross the useful range.
MAX_STEP = 0.20
# Delta at which the step reaches MAX_STEP. Above this the evidence is
# decisive and there is nothing gained by creeping.
FULL_STEP_DELTA = 0.25
# Recency window for ledger reads, in days. A repo's query distribution
# drifts as the corpus and the agent's habits change; lifetime events act
# as stale anchors that drag learned weights toward old behavior.
# 0 disables the window (lifetime ledger, pre-v1.70.0 behavior).
MAX_AGE_DAYS = 90

_TUNING_FILENAME = "tuning.jsonc"
_TUNING_LOCK = threading.Lock()
_TUNING_CACHE: dict = {}
_TUNING_CACHE_PATH: Optional[str] = None


def _tuning_path(base_path: Optional[str] = None) -> Path:
    from ..storage.paths import resolve_root  # jdoc#146
    root = resolve_root(base_path)
    root.mkdir(parents=True, exist_ok=True)
    return root / _TUNING_FILENAME


def _strip_jsonc(text: str) -> str:
    """Strip // and /* */ comments before json.loads."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def _load(base_path: Optional[str] = None) -> dict:
    global _TUNING_CACHE, _TUNING_CACHE_PATH
    path = _tuning_path(base_path)
    path_str = str(path)
    with _TUNING_LOCK:
        if _TUNING_CACHE_PATH == path_str and _TUNING_CACHE:
            return _TUNING_CACHE
        if not path.exists():
            _TUNING_CACHE = {"repos": {}}
            _TUNING_CACHE_PATH = path_str
            return _TUNING_CACHE
        try:
            raw = path.read_text(encoding="utf-8")
            data = json.loads(_strip_jsonc(raw))
            if not isinstance(data, dict):
                data = {"repos": {}}
            data.setdefault("repos", {})
            _TUNING_CACHE = data
            _TUNING_CACHE_PATH = path_str
            return _TUNING_CACHE
        except Exception:
            _TUNING_CACHE = {"repos": {}}
            _TUNING_CACHE_PATH = path_str
            return _TUNING_CACHE


def _persist(data: dict, base_path: Optional[str] = None) -> None:
    global _TUNING_CACHE, _TUNING_CACHE_PATH
    path = _tuning_path(base_path)
    header = (
        "// jdocmunch tuning overrides — auto-generated by tune_weights.\n"
        "// Hand-edits are preserved (JSONC: line and block comments allowed).\n"
    )
    body = json.dumps(data, indent=2)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with _TUNING_LOCK:
        tmp.write_text(header + body + "\n", encoding="utf-8")
        tmp.replace(path)
        _TUNING_CACHE = data
        _TUNING_CACHE_PATH = str(path)


def reset_cache() -> None:
    """Test hook — invalidate the in-memory cache."""
    global _TUNING_CACHE, _TUNING_CACHE_PATH
    with _TUNING_LOCK:
        _TUNING_CACHE = {}
        _TUNING_CACHE_PATH = None


def resolve_semantic_weight(
    repo: str,
    *,
    explicit: Optional[float] = None,
    base_path: Optional[str] = None,
) -> dict:
    """Resolve the semantic_weight for a repo AND say where it came from.

    Resolution priority:
      1. ``explicit`` — any caller value that isn't ``None``. ⚠ Unlike the
         legacy :func:`get_semantic_weight`, a caller passing exactly 0.5
         is honoured as a caller value rather than read as "unset". The
         sentinel for unset is ``None``, and only ``None``.
      2. Tuning override loaded from ``tuning.jsonc``, clamped to
         ``SEMANTIC_WEIGHT_BOUNDS``.
      3. ``DEFAULT_SEMANTIC_WEIGHT``.

    Returns ``{"weight": float, "source": str, "clamped": bool}`` where
    ``source`` is one of ``caller`` / ``tuning.jsonc`` / ``default``.

    jdoc#106: the value alone was already in ``_meta``; its PROVENANCE was
    not, so a user whose retrieval got worse after enabling embeddings had
    no way to see that a weight — default or learned — was in play. An
    out-of-bounds hand-edit is reported via ``clamped`` rather than applied
    silently.
    """
    if explicit is not None:
        return {"weight": float(explicit), "source": "caller", "clamped": False}
    data = _load(base_path)
    repos = data.get("repos") or {}
    entry = repos.get(repo) or {}
    val = entry.get("semantic_weight")
    if isinstance(val, (int, float)) and not isinstance(val, bool):
        raw = float(val)
        clamped = _clamp(raw)
        return {
            "weight": clamped,
            "source": "tuning.jsonc",
            "clamped": clamped != raw,
        }
    return {
        "weight": DEFAULT_SEMANTIC_WEIGHT,
        "source": "default",
        "clamped": False,
    }


def get_semantic_weight(
    repo: str,
    *,
    explicit: Optional[float] = None,
    base_path: Optional[str] = None,
) -> float:
    """Resolve the semantic_weight for a repo (legacy scalar form).

    Resolution priority:
      1. Explicit non-default caller value (anything that isn't ``None``
         and isn't exactly the v1.13 default 0.5).
      2. Tuning override loaded from ``tuning.jsonc``.
      3. Default 0.5.

    ⚠ Retains the pre-jdoc#106 quirk in rule 1: an explicit 0.5 is
    indistinguishable from "unset" and loses to a learned weight. Kept so
    existing callers do not change behaviour. New code should call
    :func:`resolve_semantic_weight`, which uses ``None`` as the sentinel
    and reports provenance.
    """
    if explicit is not None and explicit != DEFAULT_SEMANTIC_WEIGHT:
        return float(explicit)
    return resolve_semantic_weight(repo, explicit=None, base_path=base_path)["weight"]


def _clamp(val: float) -> float:
    lo, hi = SEMANTIC_WEIGHT_BOUNDS
    return max(lo, min(hi, val))


def _step_for(delta: float) -> float:
    """Signed step size, scaled to the strength of the measured gap.

    jdoc#106: a flat ±0.05 meant crossing the useful range took seven
    successful rounds of 50+ qualifying events each, which a real workload
    never accumulates — the documented escape hatch effectively never
    opened. The step now grows with the evidence: a delta at the decision
    threshold still moves 0.05, a decisive one moves up to MAX_STEP.

    ⚠ Deliberately still bounded. A single tuning round must never be able
    to jump the whole range on one window of events, and the sign is all we
    genuinely know — the magnitude of a confidence delta is not a
    calibrated distance to the optimum.
    """
    mag = abs(delta)
    if mag < DELTA_CONF_THRESHOLD:
        return 0.0
    # Linear ramp from STEP at the threshold to MAX_STEP at FULL_STEP_DELTA.
    span = FULL_STEP_DELTA - DELTA_CONF_THRESHOLD
    frac = 1.0 if span <= 0 else min(1.0, (mag - DELTA_CONF_THRESHOLD) / span)
    size = STEP + frac * (MAX_STEP - STEP)
    return size if delta > 0 else -size


def set_semantic_weight(
    repo: str,
    weight: float,
    *,
    base_path: Optional[str] = None,
) -> dict:
    """Persist an explicit ``semantic_weight`` for one repo.

    jdoc#106: the tuner was the only supported way to move a persisted
    weight, and it is a slow gradient walk that needs a signal a
    single-mode workload never produces. A user who has MEASURED the right
    value for their corpus — which is exactly what #106's reporter did —
    had no supported way to write it down. Hand-editing `tuning.jsonc`
    worked but is a file this module owns and rewrites.

    Returns the clamped value and whether clamping occurred; never raises
    on an out-of-range input.
    """
    requested = float(weight)
    applied = _clamp(requested)
    data = _load(base_path)
    repos = data.setdefault("repos", {})
    entry = dict(repos.get(repo) or {})
    entry["semantic_weight"] = applied
    entry["source"] = "explicit"
    entry["captured_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    entry.pop("learned_from_events", None)
    repos[repo] = entry
    _persist(data, base_path)
    return {
        "repo": repo,
        "status": "set",
        "semantic_weight": applied,
        "requested": requested,
        "clamped": applied != requested,
        "bounds": list(SEMANTIC_WEIGHT_BOUNDS),
    }


def tune_one_repo(
    repo: str,
    *,
    min_events: int = MIN_EVENTS,
    dry_run: bool = False,
    max_age_days: int = MAX_AGE_DAYS,
    base_path: Optional[str] = None,
) -> dict:
    """Compute and (optionally) persist a tuned weight for one repo."""
    window = float(max_age_days) * 86_400 if max_age_days > 0 else None
    events = ranking_db_query(
        repo=repo, limit=10000, base_path=base_path, window_seconds=window
    )
    n = len(events)
    if n < min_events:
        return {
            "repo": repo,
            "status": "insufficient_events",
            "events_seen": n,
            "min_events": min_events,
            "max_age_days": max_age_days,
        }

    confidences_with: list[float] = []
    confidences_without: list[float] = []
    for e in events:
        c = e.get("confidence")
        if c is None:
            continue
        if e.get("semantic_used"):
            confidences_with.append(float(c))
        else:
            confidences_without.append(float(c))

    if not confidences_with or not confidences_without:
        # jdoc#106: this is the common outcome, not an edge case. The tuner
        # compares modes, so a workload that only ever runs one mode can
        # never produce a signal no matter how long it runs. Saying
        # "no_signal_split" and stopping left the user with a documented
        # escape hatch that silently never opens; name the actual remedy.
        only = "semantic" if confidences_with else "lexical"
        return {
            "repo": repo,
            "status": "no_signal_split",
            "events_seen": n,
            "with_semantic": len(confidences_with),
            "without_semantic": len(confidences_without),
            "reason": (
                f"Every event in the window ran {only}-only. This tuner "
                f"learns by comparing confidence WITH vs WITHOUT the "
                f"semantic channel, so a single-mode workload yields no "
                f"signal however many events it accumulates."
            ),
            "remedy": (
                "Set the weight directly with tune_weights(set_weight=...) "
                "if you have measured the right value for this corpus, or "
                "pass semantic_weight per call."
            ),
            "current_semantic_weight": float(
                ((_load(base_path).get("repos") or {}).get(repo) or {})
                .get("semantic_weight", DEFAULT_SEMANTIC_WEIGHT)
            ),
        }

    mean_with = sum(confidences_with) / len(confidences_with)
    mean_without = sum(confidences_without) / len(confidences_without)
    delta = mean_with - mean_without

    data = _load(base_path)
    repos = data.setdefault("repos", {})
    current = float((repos.get(repo) or {}).get("semantic_weight", DEFAULT_SEMANTIC_WEIGHT))

    step = _step_for(delta)
    if step > 0:
        proposed = _clamp(current + step)
        decision = "semantic_helps"
    elif step < 0:
        proposed = _clamp(current + step)
        decision = "semantic_hurts"
    else:
        return {
            "repo": repo,
            "status": "no_significant_signal",
            "events_seen": n,
            "delta_confidence": round(delta, 4),
            "mean_with_semantic": round(mean_with, 4),
            "mean_without_semantic": round(mean_without, 4),
            "current_semantic_weight": current,
        }

    if not dry_run:
        repos[repo] = {
            "semantic_weight": proposed,
            "learned_from_events": n,
            "captured_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }
        _persist(data, base_path)

    return {
        "repo": repo,
        "status": decision,
        "events_seen": n,
        "delta_confidence": round(delta, 4),
        "mean_with_semantic": round(mean_with, 4),
        "mean_without_semantic": round(mean_without, 4),
        "previous_semantic_weight": current,
        "new_semantic_weight": proposed,
        "max_age_days": max_age_days,
        "dry_run": dry_run,
    }


def tune_all_repos(
    *,
    min_events: int = MIN_EVENTS,
    dry_run: bool = False,
    max_age_days: int = MAX_AGE_DAYS,
    base_path: Optional[str] = None,
) -> list[dict]:
    """Tune every repo with events inside the window. Empty list when none."""
    window = float(max_age_days) * 86_400 if max_age_days > 0 else None
    events = ranking_db_query(limit=100000, base_path=base_path, window_seconds=window)
    repos = sorted({e.get("repo") for e in events if e.get("repo")})
    return [
        tune_one_repo(
            repo=r,
            min_events=min_events,
            dry_run=dry_run,
            max_age_days=max_age_days,
            base_path=base_path,
        )
        for r in repos
    ]
